---
image: buluma/github-action-molecule:4.0.5
# TODO Change to local container

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

build:
  stage: build
  script:
    - echo "building..."
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"

  retry: 1
  parallel:
    matrix:
      - image: "ubuntu"
        tag: "bionic"

galaxy:
  script:
    - ansible-galaxy role info ${CI_PROJECT_NAMESPACE}.core_dependencies
