---
# tasks file for core_dependencies

- name: Remove conflicting packages
  ansible.builtin.package:
    name: "{{ core_dependencies_conflicting_packages }}"
    state: absent

- name: Install packages
  ansible.builtin.package:
    name: "{{ core_dependencies }}"
    update_cache: yes
  notify:
    - Gather facts

- name: Reset connetion
  ansible.builtin.meta: reset_connection

- name: Try to install pip packages
  ansible.builtin.pip:
    name: "{{ core_dependencies_pip_packages }}"
    state: present
  failed_when: no
  notify:
    - Gather facts

- name: Try to install xz-utils packages
  ansible.builtin.pip:
    name: xz-utils==5.4.6
    state: present
  failed_when: no
  notify:
    - Gather facts

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
