---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Compress /tmp
      community.general.archive:
        path: /tmp
        dest: tmp.tgz

    - name: Check network facts
      ansible.builtin.assert:
        that:
          - ansible_default_ipv4.broadcast is defined

    - name: See if the package manager still works
      block:
        - name: install a package
          ansible.builtin.package:
            name: acl
